import type { Menu, Option } from "@/types/menu";

const StandardSweetnessOption = (menuItemId: string): Option => ({
  id: "sweetness",
  key: "sweetness",
  name: {
    "zh-TW": "甜度",
    en: "Sweetness",
    ja: "甘さ",
    ko: "당도",
    "zh-CN": "甜度",
  },
  choices: [
    {
      id: "none",
      key: "none",
      name: {
        "zh-TW": "無糖",
        en: "No Sugar",
        ja: "無糖",
        ko: "무가당",
        "zh-CN": "无糖",
      },
      createdAt: new Date("2025-08-04T22:50:00"),
      extraCost: 0,
      ingredients: [],
      isActive: true,
      isShared: false,
      menuItemOptionId: "sweetness",
      sold: 0,
      stock: null,
      updatedAt: new Date("2025-08-04T22:50:00"),
    },
    {
      id: "micro",
      key: "micro",
      name: {
        "zh-TW": "微糖",
        en: "Micro Sugar",
        ja: "付き添い",
        ko: "조금",
        "zh-CN": "微糖",
      },
      createdAt: new Date("2025-08-04T22:50:00"),
      extraCost: 0,
      ingredients: [
        {
          id: "syrup",
          key: "syrup",
          name: {
            "zh-TW": "糖漿",
            en: "Syrup",
            ja: "シロップ",
            ko: "시럽",
            "zh-CN": "糖浆",
          },
          createdAt: new Date("2025-08-04T22:50:00"),
          menuItemOptionChoiceId: "micro",
          unit: {
            "zh-TW": "毫升",
            en: "ml",
            ja: "ミリリットル",
            ko: "밀리리터",
            "zh-CN": "毫升",
          },
          updatedAt: new Date("2025-08-04T22:50:00"),
          usage: 5,
        },
      ],
      isActive: true,
      isShared: false,
      menuItemOptionId: "sweetness",
      sold: 0,
      stock: null,
      updatedAt: new Date("2025-08-04T22:50:00"),
    },
    {
      id: "half",
      key: "half",
      name: {
        "zh-TW": "半糖",
        en: "Half Sugar",
        ja: "半糖",
        ko: "반",
        "zh-CN": "半糖",
      },
      createdAt: new Date("2025-08-04T22:50:00"),
      extraCost: 0,
      ingredients: [
        {
          id: "syrup",
          key: "syrup",
          name: {
            "zh-TW": "糖漿",
            en: "Syrup",
            ja: "シロップ",
            ko: "시럽",
            "zh-CN": "糖浆",
          },
          createdAt: new Date("2025-08-04T22:50:00"),
          menuItemOptionChoiceId: "half",
          unit: {
            "zh-TW": "毫升",
            en: "ml",
            ja: "ミリリットル",
            ko: "밀리리터",
            "zh-CN": "毫升",
          },
          updatedAt: new Date("2025-08-04T22:50:00"),
          usage: 10,
        },
      ],
      isActive: true,
      isShared: false,
      menuItemOptionId: "sweetness",
      sold: 0,
      stock: null,
      updatedAt: new Date("2025-08-04T22:50:00"),
    },
    {
      id: "less",
      key: "less",
      name: {
        "zh-TW": "少糖",
        en: "Less Sugar",
        ja: "少なめ",
        ko: "적당히",
        "zh-CN": "少糖",
      },
      createdAt: new Date("2025-08-04T22:50:00"),
      extraCost: 0,
      ingredients: [
        {
          id: "syrup",
          key: "syrup",
          name: {
            "zh-TW": "糖漿",
            en: "Syrup",
            ja: "シロップ",
            ko: "시럽",
            "zh-CN": "糖浆",
          },
          createdAt: new Date("2025-08-04T22:50:00"),
          menuItemOptionChoiceId: "less",
          unit: {
            "zh-TW": "毫升",
            en: "ml",
            ja: "ミリリットル",
            ko: "밀리리터",
            "zh-CN": "毫升",
          },
          updatedAt: new Date("2025-08-04T22:50:00"),
          usage: 15,
        },
      ],
      isActive: true,
      isShared: false,
      menuItemOptionId: "sweetness",
      sold: 0,
      stock: null,
      updatedAt: new Date("2025-08-04T22:50:00"),
    },
    {
      id: "regular",
      key: "regular",
      name: {
        "zh-TW": "正常",
        en: "Regular",
        ja: "通常",
        ko: "기본",
        "zh-CN": "正常",
      },
      createdAt: new Date("2025-08-04T22:50:00"),
      extraCost: 0,
      ingredients: [
        {
          id: "syrup",
          key: "syrup",
          name: {
            "zh-TW": "糖漿",
            en: "Syrup",
            ja: "シロップ",
            ko: "시럽",
            "zh-CN": "糖浆",
          },
          createdAt: new Date("2025-08-04T22:50:00"),
          menuItemOptionChoiceId: "regular",
          unit: {
            "zh-TW": "毫升",
            en: "ml",
            ja: "ミリリットル",
            ko: "밀리리터",
            "zh-CN": "毫升",
          },
          updatedAt: new Date("2025-08-04T22:50:00"),
          usage: 20,
        },
      ],
      isActive: true,
      isShared: false,
      menuItemOptionId: "sweetness",
      sold: 0,
      stock: null,
      updatedAt: new Date("2025-08-04T22:50:00"),
    },
  ],
  createdAt: new Date("2025-08-04T22:50:00"),
  isActive: true,
  menuItemId,
  multiple: false,
  required: true,
  updatedAt: new Date("2025-08-04T22:50:00"),
});

const StandardIceOption = (menuItemId: string): Option => ({
  id: "ice",
  key: "ice",
  name: {
    "zh-TW": "冰塊",
    en: "Ice Level",
    ja: "氷の量",
    ko: "얼음량",
    "zh-CN": "冰块",
  },
  choices: [
    {
      id: "regular",
      key: "regular",
      name: {
        "zh-TW": "正常",
        en: "Regular Ice",
        ja: "普通",
        ko: "기본",
        "zh-CN": "正常",
      },
      createdAt: new Date("2025-08-04T22:50:00"),
      extraCost: 0,
      ingredients: [],
      isActive: true,
      isShared: false,
      menuItemOptionId: "ice",
      sold: 0,
      stock: null,
      updatedAt: new Date("2025-08-04T22:50:00"),
    },
    {
      id: "less",
      key: "less",
      name: {
        "zh-TW": "少冰",
        en: "Less Ice",
        ja: "氷少なめ",
        ko: "얼음 조금",
        "zh-CN": "少冰",
      },
      createdAt: new Date("2025-08-04T22:50:00"),
      extraCost: 0,
      ingredients: [],
      isActive: true,
      isShared: false,
      menuItemOptionId: "ice",
      sold: 0,
      stock: null,
      updatedAt: new Date("2025-08-04T22:50:00"),
    },
    {
      id: "none",
      key: "none",
      name: {
        "zh-TW": "去冰",
        en: "No Ice",
        ja: "氷なし",
        ko: "얼음 없음",
        "zh-CN": "去冰",
      },
      createdAt: new Date("2025-08-04T22:50:00"),
      extraCost: 0,
      ingredients: [],
      isActive: true,
      isShared: false,
      menuItemOptionId: "ice",
      sold: 0,
      stock: null,
      updatedAt: new Date("2025-08-04T22:50:00"),
    },
    {
      id: "hot",
      key: "hot",
      name: {
        "zh-TW": "熱飲",
        en: "Hot",
        ja: "ホット",
        ko: "따뜻하게",
        "zh-CN": "热饮",
      },
      createdAt: new Date("2025-08-04T22:50:00"),
      extraCost: 0,
      ingredients: [],
      isActive: true,
      isShared: false,
      menuItemOptionId: "ice",
      sold: 0,
      stock: null,
      updatedAt: new Date("2025-08-04T22:50:00"),
    },
  ],
  createdAt: new Date("2025-08-04T22:50:00"),
  isActive: true,
  menuItemId,
  multiple: false,
  required: true,
  updatedAt: new Date("2025-08-04T22:50:00"),
});

const StandardMilkSizeOption = (menuItemId: string): Option => ({
  id: "size",
  key: "size",
  name: {
    "zh-TW": "尺寸",
    en: "Size",
    ja: "サイズ",
    ko: "사이즈",
    "zh-CN": "尺寸",
  },
  choices: [
    {
      id: "m",
      key: "m",
      name: { "zh-TW": "M", en: "M", ja: "M", ko: "M", "zh-CN": "M" },
      createdAt: new Date("2025-08-04T22:50:00"),
      extraCost: 0,
      ingredients: [
        {
          id: "milk",
          key: "milk",
          name: {
            "zh-TW": "牛奶",
            en: "Milk",
            ja: "ミルク",
            ko: "우유",
            "zh-CN": "牛奶",
          },
          createdAt: new Date("2025-08-04T22:50:00"),
          menuItemOptionChoiceId: "m",
          unit: {
            "zh-TW": "毫升",
            en: "ml",
            ja: "ミリリットル",
            ko: "밀리리터",
            "zh-CN": "毫升",
          },
          updatedAt: new Date("2025-08-04T22:50:00"),
          usage: 30,
        },
      ],
      isActive: true,
      isShared: false,
      menuItemOptionId: "size",
      sold: 0,
      stock: null,
      updatedAt: new Date("2025-08-04T22:50:00"),
    },
    {
      id: "l",
      key: "l",
      name: { "zh-TW": "L", en: "L", ja: "L", ko: "L", "zh-CN": "L" },
      createdAt: new Date("2025-08-04T22:50:00"),
      extraCost: 20,
      ingredients: [
        {
          id: "milk",
          key: "milk",
          name: {
            "zh-TW": "牛奶",
            en: "Milk",
            ja: "ミルク",
            ko: "우유",
            "zh-CN": "牛奶",
          },
          createdAt: new Date("2025-08-04T22:50:00"),
          menuItemOptionChoiceId: "l",
          unit: {
            "zh-TW": "毫升",
            en: "ml",
            ja: "ミリリットル",
            ko: "밀리리터",
            "zh-CN": "毫升",
          },
          updatedAt: new Date("2025-08-04T22:50:00"),
          usage: 60,
        },
      ],
      isActive: true,
      isShared: false,
      menuItemOptionId: "size",
      sold: 0,
      stock: null,
      updatedAt: new Date("2025-08-04T22:50:00"),
    },
  ],
  createdAt: new Date("2025-08-04T22:50:00"),
  isActive: true,
  menuItemId,
  multiple: false,
  required: true,
  updatedAt: new Date("2025-08-04T22:50:00"),
});

const StandardSnackToppingOption = (menuItemId: string): Option => ({
  id: "topping",
  key: "topping",
  name: {
    "zh-TW": "加料",
    en: "Toppings",
    ja: "トッピング",
    ko: "추가재료",
    "zh-CN": "加料",
  },
  choices: [
    {
      id: "tomato",
      key: "tomato",
      name: {
        "zh-TW": "番茄",
        en: "Tomato",
        ja: "トマト",
        ko: "토마토",
        "zh-CN": "番茄",
      },
      createdAt: new Date("2025-08-04T22:50:00"),
      extraCost: 5,
      isActive: true,
      isShared: true,
      menuItemOptionId: "topping",
      ingredients: [],
      sold: 3,
      stock: 5,
      updatedAt: new Date("2025-08-04T22:50:00"),
    },
    {
      id: "lettuce",
      key: "lettuce",
      name: {
        "zh-TW": "生菜",
        en: "Lettuce",
        ja: "レタス",
        ko: "상추",
        "zh-CN": "生菜",
      },
      createdAt: new Date("2025-08-04T22:50:00"),
      extraCost: 0,
      isActive: true,
      isShared: true,
      menuItemOptionId: "topping",
      ingredients: [],
      sold: 7,
      stock: 5,
      updatedAt: new Date("2025-08-04T22:50:00"),
    },
  ],
  createdAt: new Date("2025-08-04T22:50:00"),
  isActive: true,
  menuItemId,
  multiple: true,
  required: false,
  updatedAt: new Date("2025-08-04T22:50:00"),
});

const StandardDrinkToppingOption = (
  menuItemId: string,
  includedToppings: string[] = ["pearls", "pudding", "chia_seeds", "mint"],
): Option => {
  const allToppings = [
    {
      id: "pearls",
      key: "pearls",
      name: {
        "zh-TW": "珍珠",
        en: "Pearls",
        ja: "タピオカ",
        ko: "타피오카",
        "zh-CN": "珍珠",
      },
      createdAt: new Date("2025-08-04T22:50:00"),
      extraCost: 10,
      ingredients: [],
      isActive: true,
      isShared: true,
      menuItemOptionId: "topping",
      sold: 10,
      stock: null,
      updatedAt: new Date("2025-08-04T22:50:00"),
    },
    {
      id: "pudding",
      key: "pudding",
      name: {
        "zh-TW": "布丁",
        en: "Pudding",
        ja: "プリン",
        ko: "푸딩",
        "zh-CN": "布丁",
      },
      createdAt: new Date("2025-08-04T22:50:00"),
      extraCost: 15,
      ingredients: [],
      isActive: true,
      isShared: true,
      menuItemOptionId: "topping",
      sold: 10,
      stock: 0,
      updatedAt: new Date("2025-08-04T22:50:00"),
    },
    {
      id: "chia_seeds",
      key: "chia_seeds",
      name: {
        "zh-TW": "奇亞籽",
        en: "Chia Seeds",
        ja: "チアシード",
        ko: "치아시드",
        "zh-CN": "奇亚籽",
      },
      createdAt: new Date("2025-08-04T22:50:00"),
      extraCost: 10,
      isActive: true,
      isShared: true,
      menuItemOptionId: "topping",
      ingredients: [],
      sold: 10,
      stock: null,
      updatedAt: new Date("2025-08-04T22:50:00"),
    },
    {
      id: "mint",
      key: "mint",
      name: {
        "zh-TW": "薄荷",
        en: "Mint",
        ja: "ミント",
        ko: "민트",
        "zh-CN": "薄荷",
      },
      createdAt: new Date("2025-08-04T22:50:00"),
      extraCost: 0,
      isActive: true,
      isShared: true,
      menuItemOptionId: "topping",
      ingredients: [],
      sold: 6,
      stock: null,
      updatedAt: new Date("2025-08-04T22:50:00"),
    },
  ];

  return {
    id: "topping",
    key: "topping",
    name: {
      "zh-TW": "加料",
      en: "Toppings",
      ja: "トッピング",
      ko: "토핑",
      "zh-CN": "加料",
    },
    choices: allToppings.filter((t) => includedToppings.includes(t.key)),
    createdAt: new Date("2025-08-04T22:50:00"),
    isActive: true,
    menuItemId,
    multiple: true,
    required: false,
    updatedAt: new Date("2025-08-04T22:50:00"),
  };
};

export const menu: Menu[] = [
  {
    id: "coffee",
    key: "coffee",
    name: {
      "zh-TW": "咖啡",
      en: "Coffee",
      ja: "コーヒー",
      ko: "커피",
      "zh-CN": "咖啡",
    },
    createdAt: new Date("2025-08-04T22:50:00"),
    isActive: true,
    items: [
      {
        id: "coffee-1",
        key: "coffee-1",
        name: {
          "zh-TW": "經典拿鐵",
          en: "Classic Latte",
          ja: "クラシックラテ",
          ko: "클래식 라떼",
          "zh-CN": "经典拿铁",
        },
        createdAt: new Date("2025-08-04T22:50:00"),
        description: {
          "zh-TW": "濃醇的義式濃縮搭配綿密牛奶泡沫。",
          en: "Rich espresso with velvety milk foam.",
          ja: "濃厚なエスプレッソにふわふわのミルクフォーム。",
          ko: "진한 에스프레소와 부드러운 우유 거품.",
          "zh-CN": "浓郁的意式浓缩配绵密奶泡。",
        },
        image: "/images/IMG_4590.jpg",
        ingredients: [],
        isActive: true,
        menuId: "coffee",
        options: [
          StandardMilkSizeOption("coffee-1"),
          StandardSweetnessOption("coffee-1"),
          StandardIceOption("coffee-1"),
          StandardDrinkToppingOption("coffee-1", ["pearls", "pudding"]),
        ],
        price: 120,
        sold: 4,
        stock: null,
        updatedAt: new Date("2025-08-04T22:50:00"),
      },
      {
        id: "coffee-2",
        key: "coffee-2",
        name: {
          "zh-TW": "焦糖瑪奇朵",
          en: "Caramel Macchiato",
          ja: "キャラメルマキアート",
          ko: "카라멜 마키아토",
          "zh-CN": "焦糖玛奇朵",
        },
        createdAt: new Date("2025-08-04T22:50:00"),
        description: {
          "zh-TW": "香甜焦糖與香醇濃縮完美結合。",
          en: "Sweet caramel and rich espresso perfectly blended.",
          ja: "甘いキャラメルと濃厚なエスプレッソの完璧な組み合わせ。",
          ko: "달콤한 카라멜과 진한 에스프레소의 완벽한 조화.",
          "zh-CN": "香甜焦糖与浓郁浓缩完美结合。",
        },
        image: "/images/IMG_4590.jpg",
        ingredients: [],
        isActive: true,
        menuId: "coffee",
        options: [
          StandardMilkSizeOption("coffee-2"),
          StandardSweetnessOption("coffee-2"),
          StandardIceOption("coffee-2"),
        ],
        price: 130,
        sold: 5,
        stock: 2,
        updatedAt: new Date("2025-08-04T22:50:00"),
      },
    ],
    storeId: "store-1",
    updatedAt: new Date("2025-08-04T22:50:00"),
  },
  {
    id: "tea",
    key: "tea",
    name: {
      "zh-TW": "茶飲",
      en: "Tea",
      ja: "お茶",
      ko: "차",
      "zh-CN": "茶饮",
    },
    createdAt: new Date("2025-08-04T22:50:00"),
    isActive: true,
    items: [
      {
        id: "tea-1",
        key: "tea-1",
        name: {
          "zh-TW": "茉香綠茶",
          en: "Jasmine Green Tea",
          ja: "ジャスミン緑茶",
          ko: "자스민 녹차",
          "zh-CN": "茉香绿茶",
        },
        createdAt: new Date("2025-08-04T22:50:00"),
        description: {
          "zh-TW": "清新茉莉花香與綠茶完美融合。",
          en: "A refreshing blend of jasmine aroma and green tea.",
          ja: "爽やかなジャスミンの香りと緑茶の絶妙な組み合わせ。",
          ko: "상쾌한 자스민 향과 녹차의 완벽한 조화.",
          "zh-CN": "清新茉莉花香与绿茶完美融合。",
        },
        image: "/images/IMG_4590.jpg",
        ingredients: [],
        isActive: true,
        menuId: "tea",
        options: [StandardIceOption("tea-1"), StandardSweetnessOption("tea-1")],
        price: 80,
        sold: 9,
        stock: 20,
        updatedAt: new Date("2025-08-04T22:50:00"),
      },
      {
        id: "tea-2",
        key: "tea-2",
        name: {
          "zh-TW": "伯爵鮮奶茶",
          en: "Earl Grey Milk Tea",
          ja: "アールグレイミルクティー",
          ko: "얼그레이 밀크티",
          "zh-CN": "伯爵鲜奶茶",
        },
        createdAt: new Date("2025-08-04T22:50:00"),
        description: {
          "zh-TW": "濃醇伯爵茶搭配鮮奶，口感滑順。",
          en: "Rich Earl Grey tea with fresh milk for a smooth taste.",
          ja: "濃厚なアールグレイとミルクの滑らかな口当たり。",
          ko: "진한 얼그레이와 신선한 우유의 부드러운 조화.",
          "zh-CN": "浓醇伯爵茶搭配鲜奶，口感顺滑。",
        },
        image: "/images/IMG_4590.jpg",
        ingredients: [],
        isActive: true,
        menuId: "tea",
        options: [
          StandardMilkSizeOption("tea-2"),
          StandardIceOption("tea-2"),
          StandardSweetnessOption("tea-2"),
        ],
        price: 110,
        sold: 3,
        stock: 5,
        updatedAt: new Date("2025-08-04T22:50:00"),
      },
    ],
    storeId: "store-1",
    updatedAt: new Date("2025-08-04T22:50:00"),
  },
  {
    id: "signature",
    key: "signature",
    name: {
      "zh-TW": "招牌特調",
      en: "Signature Drinks",
      ja: "シグネチャードリンク",
      ko: "시그니처 음료",
      "zh-CN": "招牌特调",
    },
    isActive: true,
    storeId: "store-1",
    createdAt: new Date("2025-08-04T22:50:00"),
    items: [
      {
        id: "sig-1",
        key: "sig-1",
        name: {
          "zh-TW": "水果氣泡飲",
          en: "Fruit Sparkling Drink",
          ja: "フルーツスパークリング",
          ko: "과일 스파클링 음료",
          "zh-CN": "水果气泡饮",
        },
        createdAt: new Date("2025-08-04T22:50:00"),
        description: {
          "zh-TW": "新鮮水果搭配氣泡水，清爽解膩。",
          en: "Fresh fruits with sparkling water for a refreshing taste.",
          ja: "新鮮なフルーツと炭酸水で爽やかな味わい。",
          ko: "신선한 과일과 탄산수의 상쾌한 조합.",
          "zh-CN": "新鲜水果搭配气泡水，清爽解膩。",
        },
        image: "/images/IMG_4590.jpg",
        isActive: true,
        menuId: "signature",
        options: [
          StandardSweetnessOption("sig-1"),
          StandardIceOption("sig-1"),
          StandardDrinkToppingOption("sig-1", [
            "chia_seeds",
            "mint",
            "pudding",
          ]),
        ],
        price: 140,
        ingredients: [],
        sold: 2,
        stock: 3,
        updatedAt: new Date("2025-08-04T22:50:00"),
      },
      {
        id: "sig-2",
        key: "sig-2",
        name: {
          "zh-TW": "抹茶氣泡拿鐵",
          en: "Matcha Sparkling Latte",
          ja: "抹茶スパークリングラテ",
          ko: "말차 스파클링 라떼",
          "zh-CN": "抹茶气泡拿铁",
        },
        createdAt: new Date("2025-08-04T22:50:00"),
        description: {
          "zh-TW": "抹茶與牛奶氣泡完美結合。",
          en: "A refreshing fusion of matcha, milk, and sparkling water.",
          ja: "抹茶とミルク、炭酸の爽やかな融合。",
          ko: "말차, 우유, 탄산의 상쾌한 조화.",
          "zh-CN": "抹茶与牛奶气泡完美结合。",
        },
        image: "/images/IMG_4590.jpg",
        isActive: true,
        menuId: "signature",
        options: [
          StandardMilkSizeOption("sig-2"),
          StandardSweetnessOption("sig-2"),
          StandardIceOption("sig-2"),
        ],
        price: 150,
        ingredients: [],
        sold: 7,
        stock: 6,
        updatedAt: new Date("2025-08-04T22:50:00"),
      },
    ],
    updatedAt: new Date("2025-08-04T22:50:00"),
  },
  {
    id: "pastry",
    key: "pastry",
    name: {
      "zh-TW": "甜點",
      en: "Pastries",
      ja: "ペストリー",
      ko: "디저트",
      "zh-CN": "甜点",
    },
    isActive: true,
    storeId: "store-1",
    createdAt: new Date("2025-08-04T22:50:00"),
    items: [
      {
        id: "pastry-1",
        key: "pastry-1",
        name: {
          "zh-TW": "經典可頌",
          en: "Classic Croissant",
          ja: "クラシッククロワッサン",
          ko: "클래식 크루아상",
          "zh-CN": "经典可颂",
        },
        createdAt: new Date("2025-08-04T22:50:00"),
        description: {
          "zh-TW": "外酥內軟的法式可頌。",
          en: "Crispy outside and soft inside French croissant.",
          ja: "外はサクサク、中はふんわりのフランス風クロワッサン。",
          ko: "겉은 바삭하고 속은 부드러운 프랑스식 크루아상.",
          "zh-CN": "外酥内软的法式可颂。",
        },
        image: "/images/IMG_4590.jpg",
        isActive: true,
        menuId: "pastry",
        options: [],
        price: 60,
        ingredients: [],
        sold: 2,
        stock: 8,
        updatedAt: new Date("2025-08-04T22:50:00"),
      },
      {
        id: "pastry-2",
        key: "pastry-2",
        name: {
          "zh-TW": "巧克力蛋糕",
          en: "Chocolate Cake",
          ja: "チョコレートケーキ",
          ko: "초콜릿 케이크",
          "zh-CN": "巧克力蛋糕",
        },
        createdAt: new Date("2025-08-04T22:50:00"),
        description: {
          "zh-TW": "濃郁黑巧克力海綿蛋糕。",
          en: "Rich dark chocolate sponge cake.",
          ja: "濃厚なダークチョコレートのスポンジケーキ。",
          ko: "진한 다크 초콜릿 스펀지 케이크.",
          "zh-CN": "浓郁黑巧克力海绵蛋糕。",
        },
        image: "/images/IMG_4590.jpg",
        isActive: true,
        menuId: "pastry",
        options: [],
        price: 90,
        ingredients: [],
        sold: 4,
        stock: 2,
        updatedAt: new Date("2025-08-04T22:50:00"),
      },
    ],
    updatedAt: new Date("2025-08-04T22:50:00"),
  },
  {
    id: "snack",
    key: "snack",
    name: {
      "zh-TW": "輕食",
      en: "Snacks",
      ja: "軽食",
      ko: "간편식",
      "zh-CN": "輕食",
    },
    isActive: true,
    storeId: "store-1",
    createdAt: new Date("2025-08-04T22:50:00"),
    items: [
      {
        id: "snack-1",
        key: "snack-1",
        name: {
          "zh-TW": "火腿起司三明治",
          en: "Ham & Cheese Sandwich",
          ja: "ハムチーズサンドイッチ",
          ko: "햄 치즈 샌드위치",
          "zh-CN": "火腿起司三明治",
        },
        createdAt: new Date("2025-08-04T22:50:00"),
        description: {
          "zh-TW": "火腿、起司與生菜夾於法式軟包中。",
          en: "Ham, cheese, and lettuce in a soft French bun.",
          ja: "ハム、チーズ、レタスをフレンチバンズに挟んだサンド。",
          ko: "햄, 치즈, 상추를 프렌치 번에 넣은 샌드위치.",
          "zh-CN": "火腿、起司与生菜夹于法式软包中。",
        },
        image: "/images/IMG_4590.jpg",
        isActive: true,
        menuId: "snack",
        options: [StandardSnackToppingOption("snack-1")],
        price: 150,
        ingredients: [],
        sold: 8,
        stock: 0,
        updatedAt: new Date("2025-08-04T22:50:00"),
      },
      {
        id: "snack-2",
        key: "snack-2",
        name: {
          "zh-TW": "雞肉沙拉",
          en: "Chicken Salad",
          ja: "チキンサラダ",
          ko: "치킨 샐러드",
          "zh-CN": "雞肉沙拉",
        },
        createdAt: new Date("2025-08-04T22:50:00"),
        description: {
          "zh-TW": "新鮮生菜搭配香煎雞肉。",
          en: "Fresh lettuce with grilled chicken.",
          ja: "新鮮なレタスと香ばしいグリルチキンのサラダ。",
          ko: "신선한 채소와 구운 치킨이 어우러진 샐러드.",
          "zh-CN": "新鮮生菜搭配香煎雞肉。",
        },
        image: "/images/IMG_4590.jpg",
        isActive: true,
        menuId: "snack",
        options: [StandardSnackToppingOption("snack-2")],
        price: 160,
        ingredients: [],
        sold: 5,
        stock: 8,
        updatedAt: new Date("2025-08-04T22:50:00"),
      },
    ],
    updatedAt: new Date("2025-08-04T22:50:00"),
  },
];
