import {
  amber,
  blue,
  blueGrey,
  deepOrange,
  deepPurple,
  green,
  grey,
  lightBlue,
} from "@mui/material/colors";

export const STORE_LAYOUT_ORGANIZATION_SLUG = "biru";

export const STORE_LAYOUT_ROOM = {
  depth: 21,
  height: 2.8,
  width: 15.75,
} as const;

export const STORE_LAYOUT_KIND_COLORS = {
  bar: deepPurple[200],
  cold: blue[300],
  equipment: grey[200],
  front: green[300],
  heat: deepOrange[300],
  prep: amber[300],
  seat: blueGrey[200],
  storage: blueGrey[300],
  wash: lightBlue[300],
} as const;

export const STORE_LAYOUT_WALLS = [
  {
    position: [STORE_LAYOUT_ROOM.width / 2, STORE_LAYOUT_ROOM.height / 2, 0],
    rotationY: 0,
    width: STORE_LAYOUT_ROOM.width,
  },
  {
    position: [0, STORE_LAYOUT_ROOM.height / 2, STORE_LAYOUT_ROOM.depth / 2],
    rotationY: Math.PI / 2,
    width: STORE_LAYOUT_ROOM.depth,
  },
  {
    position: [
      STORE_LAYOUT_ROOM.width,
      STORE_LAYOUT_ROOM.height / 2,
      STORE_LAYOUT_ROOM.depth / 2,
    ],
    rotationY: Math.PI / 2,
    width: STORE_LAYOUT_ROOM.depth,
  },
] as const;

export const STORE_LAYOUT_PERSON_COLORS = {
  customer: blueGrey[500],
  staff: lightBlue[600],
} as const;

// 單位公尺；x 由左至右，z 由後場往顧客入口，elevation 為離地高度
export const STORE_LAYOUT_ITEMS = [
  {
    depth: 0.7,
    elevation: 0,
    height: 0.9,
    kind: "wash",
    label: "sink",
    width: 2.4,
    x: 0.3,
    z: 0.1,
  },
  {
    depth: 0.4,
    elevation: 1.5,
    height: 0.8,
    kind: "wash",
    label: "cleanShelf",
    width: 2.4,
    x: 0.3,
    z: 0.1,
  },
  {
    depth: 0.8,
    elevation: 0.75,
    height: 1,
    kind: "heat",
    label: "oven",
    width: 0.85,
    x: 3.2,
    z: 0.1,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 0.9,
    kind: "heat",
    label: "stove",
    width: 1.2,
    x: 4.3,
    z: 0.1,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 0.9,
    kind: "prep",
    label: "prepTable",
    width: 2.6,
    x: 5.9,
    z: 0.1,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 0.9,
    kind: "prep",
    label: "prepTable",
    width: 2.6,
    x: 8.7,
    z: 0.1,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 2,
    kind: "cold",
    label: "fridge",
    width: 0.8,
    x: 11.6,
    z: 0.1,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 2,
    kind: "cold",
    label: "fridge",
    width: 0.8,
    x: 12.5,
    z: 0.1,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 1.9,
    kind: "cold",
    label: "freezer",
    width: 0.8,
    x: 13.5,
    z: 0.1,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 1.9,
    kind: "cold",
    label: "freezer",
    width: 0.8,
    x: 14.4,
    z: 0.1,
  },
  {
    depth: 2.4,
    elevation: 0,
    height: 2,
    kind: "storage",
    label: "storageShelf",
    width: 0.8,
    x: 0.1,
    z: 1.4,
  },
  {
    depth: 2.4,
    elevation: 0,
    height: 2,
    kind: "storage",
    label: "storageShelf",
    width: 0.8,
    x: 14.85,
    z: 1.4,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 0.9,
    kind: "bar",
    label: "workCounter",
    width: 7,
    x: 3.4,
    z: 2.1,
  },
  {
    depth: 0.34,
    elevation: 0.9,
    height: 0.63,
    kind: "equipment",
    label: "grinder",
    width: 0.24,
    x: 3.7,
    z: 2.2,
  },
  {
    depth: 0.55,
    elevation: 0.9,
    height: 0.55,
    kind: "equipment",
    label: "espressoMachine",
    width: 0.8,
    x: 4.4,
    z: 2.2,
  },
  {
    depth: 0.35,
    elevation: 1.6,
    height: 0.3,
    kind: "bar",
    label: "cupShelf",
    width: 2.5,
    x: 3.7,
    z: 2.1,
  },
  {
    depth: 0.172,
    elevation: 0.9,
    height: 0.196,
    kind: "equipment",
    label: "kettle",
    width: 0.282,
    x: 5.5,
    z: 2.3,
  },
  {
    depth: 0.3,
    elevation: 0.9,
    height: 0.45,
    kind: "equipment",
    label: "blender",
    width: 0.25,
    x: 6.2,
    z: 2.2,
  },
  {
    depth: 0.525,
    elevation: 0.9,
    height: 0.695,
    kind: "equipment",
    label: "iceMachine",
    width: 0.35,
    x: 6.8,
    z: 2.15,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 0.9,
    kind: "bar",
    label: "workCounter",
    width: 3.6,
    x: 10.8,
    z: 2.1,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 0.9,
    kind: "wash",
    label: "returnCounter",
    width: 1.2,
    x: 0.6,
    z: 4.1,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 0.9,
    kind: "front",
    label: "passCounter",
    width: 1.8,
    x: 2.2,
    z: 4.1,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 1.1,
    kind: "bar",
    label: "frontCounter",
    width: 7.6,
    x: 4.4,
    z: 4.1,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 1.1,
    kind: "front",
    label: "orderCounter",
    width: 2,
    x: 12.4,
    z: 4.1,
  },
  {
    depth: 0.1,
    elevation: 1.1,
    height: 0.35,
    kind: "equipment",
    label: "orderScreen",
    width: 0.4,
    x: 13.2,
    z: 4.2,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 7.2,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 9.6,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 12,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 14.4,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 16.8,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 19.2,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 13.75,
    z: 7.2,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 13.75,
    z: 9.6,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 13.75,
    z: 12,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 13.75,
    z: 14.4,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 13.75,
    z: 16.8,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 13.75,
    z: 19.2,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 5.4,
    z: 8.4,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 5.4,
    z: 11.4,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 5.4,
    z: 14.4,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 5.4,
    z: 17.4,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 9.65,
    z: 8.4,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 9.65,
    z: 11.4,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 9.65,
    z: 14.4,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 9.65,
    z: 17.4,
  },
] as const;

export const STORE_LAYOUT_PEOPLE = [
  { role: "customer", x: 13.4, z: 5.4 },
  { role: "customer", x: 7.4, z: 9 },
  { role: "staff", x: 5, z: 3.4 },
  { role: "staff", x: 12.8, z: 3.4 },
  { role: "staff", x: 7.5, z: 1.4 },
] as const;

export const STORE_LAYOUT_VIEWS = {
  customer: { position: [13, 1.55, 6.6], target: [8, 1.1, 3] },
  iso: {
    position: [STORE_LAYOUT_ROOM.width + 9, 14, STORE_LAYOUT_ROOM.depth + 10],
    target: [STORE_LAYOUT_ROOM.width / 2, 1, STORE_LAYOUT_ROOM.depth / 2],
  },
  staff: { position: [9.5, 1.6, 3.4], target: [5, 1, 1.2] },
  top: {
    position: [
      STORE_LAYOUT_ROOM.width / 2,
      26,
      STORE_LAYOUT_ROOM.depth / 2 + 0.01,
    ],
    target: [STORE_LAYOUT_ROOM.width / 2, 0, STORE_LAYOUT_ROOM.depth / 2],
  },
} as const;

export const STORE_LAYOUT_AVATAR = {
  color: deepOrange[600],
  gravity: 9.8,
  jumpSpeed: 3.2,
  radius: 0.25,
  speed: 1.4,
  start: { x: STORE_LAYOUT_ROOM.width / 2, z: 20 },
} as const;
