import {
  amber,
  blue,
  blueGrey,
  deepOrange,
  deepPurple,
  green,
  grey,
  lightBlue,
} from "@mui/material/colors";

export const STORE_LAYOUT_ROOM = { depth: 7, height: 2.8, width: 9 } as const;

export const STORE_LAYOUT_KIND_COLORS = {
  bar: deepPurple[200],
  cold: blue[300],
  equipment: grey[200],
  front: green[300],
  heat: deepOrange[300],
  prep: amber[300],
  seat: blueGrey[200],
  storage: blueGrey[300],
  wash: lightBlue[300],
} as const;

export const STORE_LAYOUT_WALLS = [
  {
    position: [STORE_LAYOUT_ROOM.width / 2, STORE_LAYOUT_ROOM.height / 2, 0],
    rotationY: 0,
    width: STORE_LAYOUT_ROOM.width,
  },
  {
    position: [0, STORE_LAYOUT_ROOM.height / 2, STORE_LAYOUT_ROOM.depth / 2],
    rotationY: Math.PI / 2,
    width: STORE_LAYOUT_ROOM.depth,
  },
  {
    position: [
      STORE_LAYOUT_ROOM.width,
      STORE_LAYOUT_ROOM.height / 2,
      STORE_LAYOUT_ROOM.depth / 2,
    ],
    rotationY: Math.PI / 2,
    width: STORE_LAYOUT_ROOM.depth,
  },
] as const;

export const STORE_LAYOUT_PERSON_COLORS = {
  customer: blueGrey[500],
  staff: lightBlue[600],
} as const;

// 單位公尺；x 由左至右，z 由後場往顧客入口，elevation 為離地高度
export const STORE_LAYOUT_ITEMS = [
  {
    depth: 0.7,
    elevation: 0,
    height: 0.9,
    kind: "wash",
    label: "sink",
    width: 1.8,
    x: 0.2,
    z: 0.1,
  },
  {
    depth: 0.4,
    elevation: 1.5,
    height: 0.8,
    kind: "wash",
    label: "cleanShelf",
    width: 1.8,
    x: 0.2,
    z: 0.1,
  },
  {
    depth: 0.8,
    elevation: 0.75,
    height: 1,
    kind: "heat",
    label: "oven",
    width: 0.85,
    x: 2.2,
    z: 0.1,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 0.9,
    kind: "heat",
    label: "stove",
    width: 0.8,
    x: 3.2,
    z: 0.1,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 0.9,
    kind: "prep",
    label: "prepTable",
    width: 1.8,
    x: 4.2,
    z: 0.1,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 2,
    kind: "cold",
    label: "fridge",
    width: 0.8,
    x: 6.2,
    z: 0.1,
  },
  {
    depth: 0.8,
    elevation: 0,
    height: 1.9,
    kind: "cold",
    label: "freezer",
    width: 0.8,
    x: 7.1,
    z: 0.1,
  },
  {
    depth: 2.4,
    elevation: 0,
    height: 2,
    kind: "storage",
    label: "storageShelf",
    width: 0.8,
    x: 8.1,
    z: 0.1,
  },
  {
    depth: 0.6,
    elevation: 0,
    height: 0.9,
    kind: "bar",
    label: "workCounter",
    width: 5,
    x: 2.4,
    z: 2,
  },
  {
    depth: 0.45,
    elevation: 0.9,
    height: 0.7,
    kind: "equipment",
    label: "grinder",
    width: 0.3,
    x: 2.6,
    z: 2.1,
  },
  {
    depth: 0.55,
    elevation: 0.9,
    height: 0.55,
    kind: "equipment",
    label: "espressoMachine",
    width: 0.8,
    x: 3.3,
    z: 2.1,
  },
  {
    depth: 0.35,
    elevation: 1.6,
    height: 0.3,
    kind: "bar",
    label: "cupShelf",
    width: 2,
    x: 2.6,
    z: 2,
  },
  {
    depth: 0.3,
    elevation: 0.9,
    height: 0.45,
    kind: "equipment",
    label: "blender",
    width: 0.25,
    x: 5.4,
    z: 2.1,
  },
  {
    depth: 0.6,
    elevation: 0,
    height: 0.85,
    kind: "equipment",
    label: "iceMachine",
    width: 0.6,
    x: 5.9,
    z: 2,
  },
  {
    depth: 0.6,
    elevation: 0,
    height: 0.9,
    kind: "wash",
    label: "returnCounter",
    width: 1,
    x: 0.2,
    z: 3.5,
  },
  {
    depth: 0.6,
    elevation: 0,
    height: 0.9,
    kind: "front",
    label: "passCounter",
    width: 1.2,
    x: 1.6,
    z: 3.5,
  },
  {
    depth: 0.6,
    elevation: 0,
    height: 1.1,
    kind: "bar",
    label: "frontCounter",
    width: 4.2,
    x: 3,
    z: 3.5,
  },
  {
    depth: 0.6,
    elevation: 0,
    height: 1.1,
    kind: "front",
    label: "orderCounter",
    width: 1.2,
    x: 7.4,
    z: 3.5,
  },
  {
    depth: 0.1,
    elevation: 1.1,
    height: 0.35,
    kind: "equipment",
    label: "orderScreen",
    width: 0.4,
    x: 7.8,
    z: 3.6,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 0.6,
    z: 4.8,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 2.1,
    z: 4.8,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 0.6,
    z: 6,
  },
  {
    depth: 0.7,
    elevation: 0,
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 2.1,
    z: 6,
  },
] as const;

export const STORE_LAYOUT_PEOPLE = [
  { role: "customer", x: 8.3, z: 5.6 },
  { role: "staff", x: 2.6, z: 2.9 },
  { role: "staff", x: 4.6, z: 1.3 },
] as const;

export const STORE_LAYOUT_VIEWS = {
  customer: { position: [7.2, 1.55, 5.5], target: [4, 1.1, 2.4] },
  iso: {
    position: [STORE_LAYOUT_ROOM.width + 4, 6, STORE_LAYOUT_ROOM.depth + 5],
    target: [STORE_LAYOUT_ROOM.width / 2, 1, STORE_LAYOUT_ROOM.depth / 2],
  },
  staff: { position: [6.6, 1.6, 3.1], target: [2.6, 1, 1.6] },
  top: {
    position: [
      STORE_LAYOUT_ROOM.width / 2,
      11,
      STORE_LAYOUT_ROOM.depth / 2 + 0.01,
    ],
    target: [STORE_LAYOUT_ROOM.width / 2, 0, STORE_LAYOUT_ROOM.depth / 2],
  },
} as const;
