import {
  amber,
  blue,
  blueGrey,
  brown,
  deepOrange,
  deepPurple,
  green,
  grey,
  lightBlue,
} from "@mui/material/colors";

export const STORE_LAYOUT_ORGANIZATION_SLUG = "biru";

export const STORE_LAYOUT_ROOM = {
  depth: 21,
  height: 2.8,
  width: 15.75,
} as const;

export const STORE_LAYOUT_FLOORS = ["ground", "upper"] as const;

export const STORE_LAYOUT_KIND_COLORS = {
  bar: deepPurple[200],
  cold: blue[300],
  equipment: grey[200],
  front: green[300],
  heat: deepOrange[300],
  prep: amber[300],
  seat: blueGrey[200],
  stair: brown[300],
  storage: blueGrey[300],
  wash: lightBlue[300],
} as const;

export const STORE_LAYOUT_WALLS = [
  {
    position: [STORE_LAYOUT_ROOM.width / 2, STORE_LAYOUT_ROOM.height / 2, 0],
    rotationY: 0,
    width: STORE_LAYOUT_ROOM.width,
  },
  {
    position: [0, STORE_LAYOUT_ROOM.height / 2, STORE_LAYOUT_ROOM.depth / 2],
    rotationY: Math.PI / 2,
    width: STORE_LAYOUT_ROOM.depth,
  },
  {
    position: [
      STORE_LAYOUT_ROOM.width,
      STORE_LAYOUT_ROOM.height / 2,
      STORE_LAYOUT_ROOM.depth / 2,
    ],
    rotationY: Math.PI / 2,
    width: STORE_LAYOUT_ROOM.depth,
  },
  {
    position: [
      STORE_LAYOUT_ROOM.width / 2,
      STORE_LAYOUT_ROOM.height / 2,
      STORE_LAYOUT_ROOM.depth,
    ],
    rotationY: 0,
    width: STORE_LAYOUT_ROOM.width,
  },
] as const;

export const STORE_LAYOUT_ITEMS = [
  {
    depth: 0.7,
    elevation: 0,
    floor: "ground",
    height: 0.9,
    kind: "wash",
    label: "sink",
    width: 2.4,
    x: 0.3,
    z: 0.1,
  },
  {
    depth: 0.4,
    elevation: 1.5,
    floor: "ground",
    height: 0.8,
    kind: "wash",
    label: "cleanShelf",
    width: 2.4,
    x: 0.3,
    z: 0.1,
  },
  {
    depth: 0.8,
    elevation: 0.75,
    floor: "ground",
    height: 1,
    kind: "heat",
    label: "oven",
    width: 0.85,
    x: 3.2,
    z: 0.1,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "ground",
    height: 0.9,
    kind: "heat",
    label: "stove",
    width: 1.2,
    x: 4.3,
    z: 0.1,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "ground",
    height: 0.9,
    kind: "prep",
    label: "prepTable",
    width: 2.6,
    x: 5.9,
    z: 0.1,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "ground",
    height: 0.9,
    kind: "prep",
    label: "prepTable",
    width: 2.6,
    x: 8.7,
    z: 0.1,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "ground",
    height: 2,
    kind: "cold",
    label: "fridge",
    width: 0.8,
    x: 11.6,
    z: 0.1,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "ground",
    height: 2,
    kind: "cold",
    label: "fridge",
    width: 0.8,
    x: 12.5,
    z: 0.1,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "ground",
    height: 1.9,
    kind: "cold",
    label: "freezer",
    width: 0.8,
    x: 13.5,
    z: 0.1,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "ground",
    height: 1.9,
    kind: "cold",
    label: "freezer",
    width: 0.8,
    x: 14.4,
    z: 0.1,
  },
  {
    depth: 2.4,
    elevation: 0,
    floor: "ground",
    height: 2,
    kind: "storage",
    label: "storageShelf",
    width: 0.8,
    x: 0.1,
    z: 1.4,
  },
  {
    depth: 2.4,
    elevation: 0,
    floor: "ground",
    height: 2,
    kind: "storage",
    label: "storageShelf",
    width: 0.8,
    x: 14.85,
    z: 1.4,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "ground",
    height: 0.9,
    kind: "bar",
    label: "workCounter",
    width: 7,
    x: 3.4,
    z: 2.1,
  },
  {
    depth: 0.34,
    elevation: 0.9,
    floor: "ground",
    height: 0.63,
    kind: "equipment",
    label: "grinder",
    width: 0.24,
    x: 3.7,
    z: 2.2,
  },
  {
    depth: 0.55,
    elevation: 0.9,
    floor: "ground",
    height: 0.55,
    kind: "equipment",
    label: "espressoMachine",
    width: 0.8,
    x: 4.4,
    z: 2.2,
  },
  {
    depth: 0.35,
    elevation: 1.6,
    floor: "ground",
    height: 0.3,
    kind: "bar",
    label: "cupShelf",
    width: 2.5,
    x: 3.7,
    z: 2.1,
  },
  {
    depth: 0.172,
    elevation: 0.9,
    floor: "ground",
    height: 0.196,
    kind: "equipment",
    label: "kettle",
    width: 0.282,
    x: 5.5,
    z: 2.3,
  },
  {
    depth: 0.3,
    elevation: 0.9,
    floor: "ground",
    height: 0.45,
    kind: "equipment",
    label: "blender",
    width: 0.25,
    x: 6.2,
    z: 2.2,
  },
  {
    depth: 0.525,
    elevation: 0.9,
    floor: "ground",
    height: 0.695,
    kind: "equipment",
    label: "iceMachine",
    width: 0.35,
    x: 6.8,
    z: 2.15,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "ground",
    height: 0.9,
    kind: "bar",
    label: "workCounter",
    width: 3.6,
    x: 10.8,
    z: 2.1,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "ground",
    height: 0.9,
    kind: "wash",
    label: "returnCounter",
    width: 1.2,
    x: 0.6,
    z: 4.1,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "ground",
    height: 0.9,
    kind: "front",
    label: "passCounter",
    width: 1.8,
    x: 2.2,
    z: 4.1,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "ground",
    height: 1.1,
    kind: "bar",
    label: "frontCounter",
    width: 7.6,
    x: 4.4,
    z: 4.1,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "ground",
    height: 1.1,
    kind: "front",
    label: "orderCounter",
    width: 2,
    x: 12.4,
    z: 4.1,
  },
  {
    depth: 0.1,
    elevation: 1.1,
    floor: "ground",
    height: 0.35,
    kind: "equipment",
    label: "orderScreen",
    width: 0.4,
    x: 13.2,
    z: 4.2,
  },
  {
    depth: 0.6,
    elevation: 0,
    floor: "upper",
    height: 0.9,
    kind: "wash",
    label: "returnCounter",
    width: 1.7,
    x: 13.95,
    z: 5,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "ground",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 7.2,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "ground",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 9.6,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "ground",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 12,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "ground",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 14.4,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "ground",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 16.8,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "ground",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 19.2,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "ground",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 13.75,
    z: 12,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "ground",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 13.75,
    z: 14.4,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "ground",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 13.75,
    z: 16.8,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "ground",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 13.75,
    z: 19.2,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "ground",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 5.4,
    z: 8.4,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "ground",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 5.4,
    z: 11.4,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "ground",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 5.4,
    z: 14.4,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "ground",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 5.4,
    z: 17.4,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "ground",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 9.65,
    z: 8.4,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "ground",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 9.65,
    z: 11.4,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "ground",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 9.65,
    z: 14.4,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "ground",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 9.65,
    z: 17.4,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 0.6,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 3,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 5.4,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 7.8,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 10.2,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 12.6,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 15,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 17.4,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 0.6,
    z: 19.8,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 13.75,
    z: 0.6,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 13.75,
    z: 3,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 13.75,
    z: 12.6,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 13.75,
    z: 15,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 13.75,
    z: 17.4,
  },
  {
    depth: 0.8,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 1.4,
    x: 13.75,
    z: 19.8,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 5.4,
    z: 1,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 5.4,
    z: 4,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 5.4,
    z: 7,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 5.4,
    z: 10,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 5.4,
    z: 13,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 5.4,
    z: 16,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 5.4,
    z: 19,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 9.65,
    z: 1,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 9.65,
    z: 4,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 9.65,
    z: 7,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 9.65,
    z: 10,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 9.65,
    z: 13,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 9.65,
    z: 16,
  },
  {
    depth: 0.7,
    elevation: 0,
    floor: "upper",
    height: 0.75,
    kind: "seat",
    label: "table",
    width: 0.7,
    x: 9.65,
    z: 19,
  },
] as const;

export const STORE_LAYOUT_VIEWS = {
  first: { eye: 1.55, lookAhead: 1 },
  follow: { eye: 1.55, offset: [0, 1.2, 3.2] },
  iso: {
    position: [STORE_LAYOUT_ROOM.width + 9, 14, STORE_LAYOUT_ROOM.depth + 10],
    target: [STORE_LAYOUT_ROOM.width / 2, 1, STORE_LAYOUT_ROOM.depth / 2],
  },
  top: {
    position: [
      STORE_LAYOUT_ROOM.width / 2,
      26,
      STORE_LAYOUT_ROOM.depth / 2 + 0.01,
    ],
    target: [STORE_LAYOUT_ROOM.width / 2, 0, STORE_LAYOUT_ROOM.depth / 2],
  },
} as const;

export const STORE_LAYOUT_VIEW_ORDER = [
  "iso",
  "top",
  "follow",
  "first",
] as const satisfies readonly (keyof typeof STORE_LAYOUT_VIEWS)[];

export const STORE_LAYOUT_AVATAR = {
  color: deepOrange[600],
  gravity: 9.8,
  jumpSpeed: 3.2,
  radius: 0.25,
  speed: 1.4,
  start: { x: STORE_LAYOUT_ROOM.width / 2, z: 20 },
} as const;

export const STORE_LAYOUT_FLOOR_HEIGHT = 3.05;

export const STORE_LAYOUT_SLAB_THICKNESS = 0.25;

const STAIR_X = 13.95;
const STAIR_Z = 6.6;
const STAIR_WIDTH = 1.7;
const STAIR_TREAD = 0.27;
const STAIR_FLIGHT_TREADS = 8;
const STAIR_LANDING_DEPTH = 1.2;
const STAIR_RISER = STORE_LAYOUT_FLOOR_HEIGHT / 17;

const STAIR_FLIGHT_WIDTH = STAIR_WIDTH / 2;
const STAIR_FLIGHT_RUN = STAIR_FLIGHT_TREADS * STAIR_TREAD;
const STAIR_LANDING_Z = STAIR_Z + STAIR_FLIGHT_RUN;

const flightTreads = (count: number) =>
  Array.from({ length: STAIR_FLIGHT_TREADS }, (_, index) => index + 1).map(
    (tread) => ({
      depth: STAIR_TREAD,
      top: (count + tread) * STAIR_RISER,
      width: STAIR_FLIGHT_WIDTH,
      x: count ? STAIR_X + STAIR_FLIGHT_WIDTH : STAIR_X,
      z: count
        ? STAIR_LANDING_Z - tread * STAIR_TREAD
        : STAIR_Z + (tread - 1) * STAIR_TREAD,
    }),
  );

export const STORE_LAYOUT_STAIR_STEPS = [
  ...flightTreads(0),
  {
    depth: STAIR_LANDING_DEPTH,
    top: STAIR_FLIGHT_TREADS * STAIR_RISER,
    width: STAIR_WIDTH,
    x: STAIR_X,
    z: STAIR_LANDING_Z,
  },
  ...flightTreads(STAIR_FLIGHT_TREADS),
];

export const STORE_LAYOUT_STAIRWELL = {
  depth: STAIR_FLIGHT_RUN + STAIR_LANDING_DEPTH,
  width: STAIR_WIDTH,
  x: STAIR_X,
  z: STAIR_Z,
} as const;

export const STORE_LAYOUT_STAIR_EXIT = {
  x: STAIR_X + STAIR_FLIGHT_WIDTH / 2,
  z: STAIR_Z - 0.5,
} as const;

export const STORE_LAYOUT_SLAB_PANELS = [
  {
    depth: STORE_LAYOUT_STAIRWELL.z,
    width: STORE_LAYOUT_ROOM.width,
    x: 0,
    z: 0,
  },
  {
    depth:
      STORE_LAYOUT_ROOM.depth -
      STORE_LAYOUT_STAIRWELL.z -
      STORE_LAYOUT_STAIRWELL.depth,
    width: STORE_LAYOUT_ROOM.width,
    x: 0,
    z: STORE_LAYOUT_STAIRWELL.z + STORE_LAYOUT_STAIRWELL.depth,
  },
  {
    depth: STORE_LAYOUT_STAIRWELL.depth,
    width: STORE_LAYOUT_STAIRWELL.x,
    x: 0,
    z: STORE_LAYOUT_STAIRWELL.z,
  },
  {
    depth: STORE_LAYOUT_STAIRWELL.depth,
    width:
      STORE_LAYOUT_ROOM.width -
      STORE_LAYOUT_STAIRWELL.x -
      STORE_LAYOUT_STAIRWELL.width,
    x: STORE_LAYOUT_STAIRWELL.x + STORE_LAYOUT_STAIRWELL.width,
    z: STORE_LAYOUT_STAIRWELL.z,
  },
];

export const STORE_LAYOUT_STAIR_GUARD_HEIGHT = 0.9;

const STAIR_GUARD_THICKNESS = 0.08;

// 第一段只擋上行梯段那半邊，剩下的半邊是出梯口；補成整寬會把二樓封死，上不去也下不來
export const STORE_LAYOUT_STAIR_GUARDS = [
  {
    depth: STAIR_GUARD_THICKNESS,
    width: STAIR_FLIGHT_WIDTH,
    x: STORE_LAYOUT_STAIRWELL.x,
    z: STORE_LAYOUT_STAIRWELL.z - STAIR_GUARD_THICKNESS,
  },
  {
    depth: STORE_LAYOUT_STAIRWELL.depth,
    width: STAIR_GUARD_THICKNESS,
    x: STORE_LAYOUT_STAIRWELL.x - STAIR_GUARD_THICKNESS,
    z: STORE_LAYOUT_STAIRWELL.z,
  },
  {
    depth: STORE_LAYOUT_STAIRWELL.depth,
    width: STAIR_GUARD_THICKNESS,
    x: STORE_LAYOUT_STAIRWELL.x + STORE_LAYOUT_STAIRWELL.width,
    z: STORE_LAYOUT_STAIRWELL.z,
  },
  {
    depth: STAIR_GUARD_THICKNESS,
    width: STORE_LAYOUT_STAIRWELL.width,
    x: STORE_LAYOUT_STAIRWELL.x,
    z: STORE_LAYOUT_STAIRWELL.z + STORE_LAYOUT_STAIRWELL.depth,
  },
];

export const STORE_LAYOUT_FLOOR_BASE = Object.fromEntries(
  STORE_LAYOUT_FLOORS.map((floor, index) => [
    floor,
    index * STORE_LAYOUT_FLOOR_HEIGHT,
  ]),
) as Record<(typeof STORE_LAYOUT_FLOORS)[number], number>;

export const STORE_LAYOUT_FLOOR_ENTRY = {
  ground: STORE_LAYOUT_AVATAR.start,
  upper: STORE_LAYOUT_STAIR_EXIT,
} as const satisfies Record<
  (typeof STORE_LAYOUT_FLOORS)[number],
  { x: number; z: number }
>;
