// https://nextjs.org/docs/app/building-your-application/routing/internationalization

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import AppLayout from "./appLayout";
import { getDictionary } from "./dictionaries";
import Providers from "./providers";

import { LocaleCode } from "@/types/locale";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Biru Coffee Admin",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [
    { lang: "zh-TW" },
    { lang: "zh-CN" },
    { lang: "en" },
    { lang: "ja" },
    { lang: "ko" },
  ];
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: LocaleCode }>;
}>) {
  const { lang } = await params;
  const dict = await getDictionary(lang);

  return (
    <html lang={lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers dict={dict}>
          <AppLayout>{children}</AppLayout>
        </Providers>
      </body>
    </html>
  );
}
